### ISSUE TITLE
Night Slashers loud sound, gfx issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#1127]
Night Slashers music volume is really loud.

When you do a special with the girl, the flames that cover the whole screen should be transparent and you should be able to still see the background.
The game reacts on the 1st frame in FBN, Mame takes 2, if you have to add a frame for that and don't want to feel too bad about it.

**Comment by dinkc64** [comment]
Hong Hua's special is fixed, thanks for the bug report!

**Comment by Tatsuya79** [comment]
Thank you but there's still a problem with it.
On stage 2, the forest with the fog, you don't see the flames when doing the special, it's just red and flickering.

**Comment by dinkc64** [comment]
Thanks for spotting that, I've updated the fix to handle that scene.

best regards,
- dink

**Comment by Tatsuya79** [comment]
Thank you. 😃 

What do you think about the audio? The music sounds really loud and covers the SE.
PCB video recording: https://youtu.be/mRlrQF7FNFM?t=92

**Comment by dinkc64** [comment]
I don't get it? I think it sounds perfect on my side.

**Comment by barbudreadmon** [comment]
Different audio settings maybe ? The libretro port defaults to 48k + interpolation.

**Comment by dinkc64** [comment]
same here, I do have super hi.q phones though.  basically, this is what I'm up against:
-how it is now-
start game of nightslashers
music is loud and f* awesome!
it's time to kick ass!

-after tweaking volume-
start game of nightslashers
let's take a nap!

If you can figure that one out, I'm all.. ears, I guess? :)

**Comment by dinkc64** [comment]
maybe an idea:  create a new dip called Grandparents mode?

**Comment by dinkc64** [comment]
Nevermind my silly comments, I'll try to find a nice solution tomorrow.

best regards,
- dink

**Comment by dinkc64** [comment]
Honestly, I think it's the lowpassfilter function that makes this game sound so great with the current volume settings.

**Comment by dinkc64** [comment]
reduced the second oki msm6295's volume by .10, this chip played the guitar samples for the music.  by doing this, it made the sfx a bit more clear.

**Comment by Tatsuya79** [comment]
Thank you , closing it: 👍

**Comment by dinkc64** [comment]
just a tip: try with the lp filter on - it really makes this game shine (if sound were light) :)

best regards,
- dink
