### ISSUE TITLE
Eagle Shot Golf (eaglshot) is corrupted

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#117]
It's seems the eagle shot golf are corrupted and make them unplayable on FB Neo but not on Mame.
![eaglshot-191002-000720](https://user-images.githubusercontent.com/37503397/65980008-e9d1f300-e4a8-11e9-9433-c3784af438f9.png)
![eaglshot-191002-000738](https://user-images.githubusercontent.com/37503397/65980042-f9513c00-e4a8-11e9-9f76-74f3ba86f18c.png)

**Comment by dinkc64** [comment]
Panderner, it is running OK for me, are you running the latest gcc-built exe?

**Comment by barbudreadmon** [comment]
I can't reproduce either, maybe you have a corrupted rom or something ? Are you using standalone or libretro ? Are you using any specific setting ?

**Comment by Panderner** [comment]
Libretro I'm using android

**Comment by Panderner** [comment]
And the rom is not corrupted. The Mame works flawlessly

**Comment by barbudreadmon** [comment]
@Panderner when writing an issue, you should always be precise about the platform you are using, especially in this case where you report this on standalone FBNeo's github which is x86 windows only...

I get some corruption on linux arm, it seems very different and minimal when compared to your screenshot though, is your device arm or aarch64 ?

**Comment by Loggan08** [comment]
Seems fine over here, running c924c108 vc_x64 build.

https://i.imgur.com/TpenlEk.png

**Comment by Panderner** [comment]
aarch64

**Comment by barbudreadmon** [comment]
@dinkc64 i investigated further into this issue, not 100% sure this is the same as the OP since we aren't using the same arch (arm & aarch64), but they might be related and here is what i discovered : 

First i added the following code to `d_ssv.cpp` : 
```
@@ -3580,6 +3580,8 @@
 			sx      =       s2[ 2 ];
 			sy      =       s2[ 3 ];
 
+			bprintf(0, _T("frame %d: num %x sx %x sy %x\n"), nCurrentFrame, num, sx, sy);
+
 			local_depth     =   sx & 0xf000;
 			local_xnum      =   sx & 0x0c00;
 			local_ynum      =   sy & 0x0c00;
```

Here is the diff of the debug output from x64 to arm : https://pastebin.com/ffZpDksd

Seems to me like `spriteram16` has different content on both arch, while i understand this ptr is provided by the v60 cpu, i'm not sure what it could mean.

@Panderner could you try other games from the SSV driver and let me know if you experience similar issues ? On my side i didn't find any game besides `eaglshot` that seemed corrupted, here is a list : 
```
cairblad
keithlcy
drifto94
dynagear
eaglshotj
eaglshot
ryorioh
koikois2
janjans1
janjans2
hypreact
hypreac2
meosism
gdfs
mslider
sxyreact
sxyreac2
pastelis
stmbladej
stmblade
srmp7
srmp4
srmp4o
survartsj
survartsu
survarts
twineag2
ultraxg
ultrax
vasara2
vasara2a
vasara

```

**Comment by dinkc64** [comment]
It looks like spriteram is getting corrupted somehow.  hmm,
try this:
get to the same point (attract) in the windows version, put:
BurnDump("sprram.bin", DrvSprRAM, 0x40000);
 at the top of DrvDraw()
here's the file from windows:
[sprram.zip](https://github.com/finalburnneo/FBNeo/files/3694388/sprram.zip)

then on the arm version, put BurnDumpLoad("sprram.bin", DrvSprRAM, 0x40000);
at the top of DrvDraw() and also copy the sprram.bin from the windows (or working) version, and see if that fixes the display using a static dump of the sprite ram.

**Comment by grant2258** [comment]
try add -fsigned-char details here https://trofi.github.io/posts/203-signed-char-or-unsigned-char.html

**Comment by barbudreadmon** [comment]
@grant2258 that's not the issue here, actually emulation code in FBNeo doesn't use `char` (only `signed char` or `unsigned char`, except for strings). I also checked for negative float to unsigned int implicit conversion (a less known difference between arm & x86, check https://github.com/finalburnneo/FBNeo/commit/9c0fef410c9aa8afbfe576a7075192d1f653d579)

@dinkc64 i tried dumping my `DrvSprRAM` and diffing it with yours, mine is definitely corrupted... kinda weird since loading yours doesn't fix the visual corruption though.
Mine for frame 1616 : [sprram2.zip](https://github.com/finalburnneo/FBNeo/files/3703540/sprram2.zip)

**Comment by dinkc64** [comment]
To rule something out, would you try to compile it all as 32bit and see how it works with my sprram and scroll ram dumps loaded on your side, at the top of DrvDraw? 

btw, I tried your sprram on my side and there is definitely something wrong with it.

**Comment by Panderner** [comment]
Other ssv games works great on my aarch64

**Comment by barbudreadmon** [comment]
@Panderner same as me then, so probably the same bug, it is really weird, @dinkc64 and me spent quite some time trying to figure this one out but we have no idea why the sprite ram gets corrupted.

**Comment by Panderner** [comment]
Yeah when I trying to go to in-game is the game freezes or watchdog crash
![eaglshot-191101-174755](https://user-images.githubusercontent.com/37503397/68016670-fe83ef80-fccf-11e9-8e2a-9c41fd09cced.png)
![eaglshot-191031-184705](https://user-images.githubusercontent.com/37503397/68016703-122f5600-fcd0-11e9-9ed2-04bcd3ae2ad6.png)

**Comment by dinkc64** [comment]
if the emulator crashes then maybe there is a memory fault (ub) somewhere?

**Comment by barbudreadmon** [comment]
Interesting, i'll try to build an aarch64 testbed to see what the crash is about.

**Comment by barbudreadmon** [comment]
I'm not getting the same issue on linux aarch64, if the result is different between android & linux on the same arch, i think the corruption might be coming from either the frontend (RA) or the libretro port itself (maybe some kind of string operation ?)

**Comment by dinkc64** [comment]
please paste the log on pastebin for compiling d_ssv.cpp on aarch64, maybe I can recognize something.

**Comment by grant2258** [comment]
only thing I seen on x64 compile for windows is 

../../burner/libretro/libretro-common/include/retro_environment.h:105:5: warning: "_M_IX86_FP" is not defined, evaluates to 0 [-Wundef]
 #if _M_IX86_FP == 1
     ^~~~~~~~~~
../../burner/libretro/libretro-common/include/retro_environment.h:107:7: warning: "_M_IX86_FP" is not defined, evaluates to 0 [-Wundef]
 #elif _M_IX86_FP == 2 || (defined(_M_AMD64) || defined(_M_X64))

**Comment by grant2258** [comment]
Nothing showing up on asan but there is a problem on the pi

![eaglshot-191105-003034](https://user-images.githubusercontent.com/6128601/68169461-2a1f0800-ff64-11e9-8401-37ec25b334f9.png)


compile log you asked for can only do this for arm somone else will have to do aarch64.
https://pastebin.com/DDGYyguz

**Comment by dinkc64** [comment]
thanks, we already have logs from pi though.

**Comment by barbudreadmon** [comment]
@dinkc64 Sadly nothing new after sanitizing dipswitch's `-Wformat-truncation` warnings in the libretro code (i had hope it would be something about them, considering some strings might have been unusually long for this game).

@grant2258 The `-Wwrite-strings` warnings should be harmless (fbalpha started using `-Wno-write-strings` a long time ago to avoid those). Both ASAN & UBSAN were ran. My odroid N2 (linux aarch64) gave me exactly the same result (which seems to be different from android). We spent quite some time checking things in d_ssv.cpp with dink, i don't think the issue is in there at this point.

Idk if the issue could come from RA ? The way it acts differently from a platform to another (both aarch64) while there is no platform-specific code in fbneo makes me wonder. Otherwise, the likely suspect would be the v60 (st0020 is not in use for this game, es5506 seems too widely used for this to happen only on this game, and i don't think the upd7725 is in use here either), but idk where i should look at in there.

**Comment by dinkc64** [comment]
It's just an idea, but:
Can you try the d_ssv.cpp from the version @ this commit: https://github.com/finalburnneo/FBNeo/commit/7be7ca4f3afc37e2a4f201a192c5b27a2bb8b1c5#diff-d6d38dad7adca235f060d9c0e51a0941
this is before the updated drawing stuff from Pastel Island
If that still has the issue, go back a little further in the d_ssv history and try the one from before the eagle shot "end of round" message fix.

**Comment by barbudreadmon** [comment]
No, the issue was already there before those 2 commits.

**Comment by grant2258** [comment]
im pretty new to the code base so ill mes about a bit I want to find out why some drivers dont give this error and others dont hopefully it just a missing header or something. For tinkering about a bit i think it something to do with tchar but thats just a guess at this point. I think ill try rule out 64 bit linux  as well. If it fails it might just be a linux issue. Ill compile RA with asan as well for the pi see if anything shows up.

**Comment by barbudreadmon** [comment]
`TCHAR` is only used for strings and typedefed as `char`, `char` is expected for strings whatever the arch but feel free to tinker with it.

**Comment by grant2258** [comment]
most error seem to be coming from here. https://github.com/finalburnneo/FBNeo/blob/a4749700b49da6fdbfa45931f2d740bb79ea2c20/src/burn/state.h#L41-L52 

ill try change that to const char

**Comment by dinkc64** [comment]
barbudreadmon, good to know I didn't cause it with the changes then :)
I wish I could somehow force this problem to happen on my side.  Bugs w/o a reproduce are very hard to fix, especially as huge as that driver is..  
A new idea to try:
hard-disable _all_ code that links to game's memory:
states,
cheevos
cheats(?)
the code that counts up the state memory to find the mainram.
best regards,
- dink

**Comment by barbudreadmon** [comment]
I tried disabling all savestate-related calls last month (including the one for saving service settings in some games - not this one though), it didn't help. @grant2258 scanvar is only used in those calls, so it's most likely unrelated to the corruption issue.

FWIW, i also tried backporting https://github.com/mamedev/mame/commit/6b3a98637c513a38515236790f48f63b32e72cef#diff-95656de9095a0a392bba4c69906417b6 since it was about signed char stuff, it didn't help.

**Comment by grant2258** [comment]
yea was more what was causing these errors the const char fixes it if you add it to burn.h and burnint.h and state.h these errors go away. I tried pc linux64 bit was fine is a strange one would need to track it down.

**Comment by barbudreadmon** [comment]
@dinkc64 i disabled upd96050, upd7725, es5506, the scan function, and SSV_UPD_SPEEDHACK, it's still happening xD.
It looks like a v60 issue to me.

**Comment by barbudreadmon** [comment]
I spent way too much time on this again, actually v60 seems fine to me (comparing to MAME's). At this point i don't think the issue could be anywhere besides the `eaglshot_*` functions, but MAME's ssv driver looks way too different so it won't help me debugging this.

**Comment by dinkc64** [comment]
Another idea: next meet-up we'll log all reads and writes and compare logs to find the deviation.

**Comment by grant2258** [comment]
some info here on fixing this for mame2003 plus could be driver or cpu related but since gdfs is working im guessing is might be driver related

**Comment by grant2258** [comment]
@dink i can confirm this code disabled in mame2003-plus https://github.com/grant2258/mame2003-plus-barcade/blob/36e104cbbd18d92d2b387a62ef01b7081e707bf2/src/drawgfx.c#L30-L62 renders the game the same as fbneo on the arm

**Comment by dinkc64** [comment]
grant2258, thanks for looking into this, I will see what can be done similarly on our side.

**Comment by dinkc64** [comment]
I made a testfix for this, please give it a try
@barbudreadmon try it also ? :)
[d_ssv.zip](https://github.com/finalburnneo/FBNeo/files/3993650/d_ssv.zip)

**Comment by grant2258** [comment]
will test this after work and get back to you

**Comment by dinkc64** [comment]
I found out early that it doesn't work (thanks barbudreadmon), on to the next idea

**Comment by barbudreadmon** [comment]
> i can confirm this code disabled in mame2003-plus

Can you confirm what you did exactly ? In the first place, it doesn't seem `ALIGN_INTS` is ever defined in this repo so https://github.com/grant2258/mame2003-plus-barcade/blob/36e104cbbd18d92d2b387a62ef01b7081e707bf2/src/drawgfx.c#L32-L58 should never be in use.

**Comment by grant2258** [comment]
I removed the if condition and compiled mame2003-plus and the gfx where corrupted the same

**Comment by barbudreadmon** [comment]
Which if ? There are several of them in the code you posted, can you provide a diff of the exact changes you did ? Also, when you say the gfx got corrupted the same, are you talking about the ss from the OP or are you talking about the ss with the quarter screen painted in pink ?

**Comment by grant2258** [comment]
The bit painted pink thing is i updated the pi binary from retropie and its pink there as well. Im going to try compiling it with retropie setup script because i didnt use that when i compiled this one just used the command line. It did work before when we where testing this is strange. I removed everything before the else.

**Comment by barbudreadmon** [comment]
I figured out the issue, it was exactly the same as raiden2 (cast of negative float to unsigned int), it seems i didn't see this one when i first reviewed the code : 
https://github.com/finalburnneo/FBNeo/blob/5716b35ac9e16c13c1cd624ec1a0b04679025465/src/cpu/v60/op2.c#L79

Replacing this by `modWriteValW = (INT32)val;` seems to solve the issue on aarch64, however before commiting anything i want confirmation it can't cause some issue elsewhere (and that it solves this on arm too)

**Comment by grant2258** [comment]
is working on the pi. Its strange this was working before on plus. I did look up this bug you are talking about and it seems it is undefined behavior. https://stackoverflow.com/questions/4752315/coercing-float-into-unsigned-char-on-arm-vs-intel

**Comment by dinkc64** [comment]
@barbudreadmon, congrats on the fix!!!! :)  Please commit it!

**Comment by barbudreadmon** [comment]
> it seems it is undefined behavior

Yeah, but for whatever reason ubsan doesn't say anything about those, the first time i heard about this was when i was trying to fix an issue on raiden2's first boss's legs.

Fix committed, finally closing this issue :)

**Comment by Panderner** [comment]
I updated to latest version still not fixed
![eaglshot-191228-223811](https://user-images.githubusercontent.com/37503397/71545165-c1339980-29c2-11ea-902b-7ed6fb739e47.png)
I'm using Realme C2

**Comment by grant2258** [comment]
what is the github commit version you updated too?

**Comment by Panderner** [comment]
> what is the github commit version you updated too?

It's 26f6bf4

**Comment by grant2258** [comment]
is that the retroarch one? goto load core then load fbneo it should say the commit number at the bottom

**Comment by barbudreadmon** [comment]
rofl, reopening then, however i'm not sure i'll be able to fix this if i can't reproduce it on arm linux

**Comment by Panderner** [comment]
> is that the retroarch one? goto load core then load fbneo it should say the commit number at the bottom
> 
> edit: my bad is up to date with the libretro core didnt realize it had its own fork the fix is working on the pi no idea wat going on there

Yes I'm using retroarch

**Comment by grant2258** [comment]
@barbudreadmon  there is more than once instance of the uint32 with the float. Do you want to change them all. Im going to see if i can get mame stand alone compiled in arm and see if it has the same side effects at some point because the current mame v60 code is using the uint for the floats.

**Comment by dinkc64** [comment]
oh bummer, i bet it is one of those other uint32 -> int32 needs to be changed

**Comment by barbudreadmon** [comment]
Hmmmm we could try, however i think the negative float to unsigned issue should happen the same on any arm device.
@Panderner btw, when does this screen happen ? directly at launch or do you have a normal launch before this ? if so, can you describe or capture the boot ?

**Comment by grant2258** [comment]
found this handy dandy doc.

https://docs.microsoft.com/en-us/cpp/build/common-visual-cpp-arm-migration-issues?view=vs-2019
```
These platforms also differ in how they handle conversion of NaN (Not-a-Number) to integer types. On ARM, NaN converts to 0x00000000; on x86 and x64, it converts to 0x80000000.
```
https://github.com/finalburnneo/FBNeo/blob/a2b6702caf01d61a38894088303b89c5f58f0a5a/src/cpu/v60/op2.c#L83

try this code 

https://github.com/grant2258/FBNeo/commit/9920a6f14f4516f2f567481d22537771461bc499

**Comment by barbudreadmon** [comment]
I probably fixed the original issue in my last commit (should be available from the libretro buildbot soon), actually it was about clang (which is the compiler for android) reacting differently from gcc about an overflow.
Waiting for @Panderner's confirmation before closing.

**Comment by Panderner** [comment]
We did it the game's fixed on latest commit. It's now playable now
![eaglshot-200123-221507](https://user-images.githubusercontent.com/37503397/72991981-ec789f80-3e2d-11ea-8511-5bab5dd6a55e.png)

I'm closing now.

**Comment by dinkc64** [comment]
woohoo! :)
