### ISSUE TITLE
Battle Chopper (World) not working

### ISSUE THREAD

**Issue by gegecom83** [finalburnneo/FBNeo#1280]
Hello
Irem "bchopper" Battle Chopper (World) game not working.

Thank you

Debug log created by FinalBurn Neo [DEBUG] v1.0.0.03 on Thu Dec 29 16:44:28 2022

 ** Translation disabled
 ** Enabling High-Resolution system timer.
 ** Enumerating available DirectDraw drivers:
 ** Starting Direct3D7 blitter.
  * Initialising video: Total video memory minus display surface: 112.50MB.
  * Initialisation complete: 104.28MB video memory free.
    Displaying and rendering in 32-bit mode, emulation running in 32-bit mode.
    Running in windowed mode, using Blt() to transfer the final image.
[Win7+] Sync to DWM is enabled (if available).
SuperWaitVBlankInit() on \\.\DISPLAY1
*** Information message:
    bchopper was found (roms/arcade/bchopper).
    The ROMset is OK.
*** Starting emulation of bchopper - Battle Chopper (World).
BurnSetMouseDivider() @ 1
Cheat cpu-register INIT.
Loading i8751 MCU @ 23 - size 10000
BurnYM2151Exit called without init
DACExit called without init
ZetExit called without init
VezExit called without init
*** Warning message:
    There was a problem starting 'Battle Chopper (World)'.
 ** Enumerating available DirectDraw drivers:
 ** Starting Direct3D7 blitter.
  * Initialising video: Total video memory minus display surface: 112.50MB.
  * Initialisation complete: 104.28MB video memory free.
    Displaying and rendering in 32-bit mode, emulation running in 32-bit mode.
    Running in windowed mode, using Blt() to transfer the final image.
[Win7+] Sync to DWM is enabled (if available).
SuperWaitVBlankInit() on \\.\DISPLAY1

**Comment by dinkc64** [comment]
Hi,
Thanks for your bug report, problem is fixed :)

**Comment by gegecom83** [comment]
Hi
I still have the same error with the latest version
Thank you

**Comment by dinkc64** [comment]
sorry about that, it should be fine now :)

**Comment by gegecom83** [comment]
Thank you it works
