### ISSUE TITLE
Some more Genre corrections

### ISSUE THREAD

**Issue by Goratrix** [finalburnneo/FBNeo#1647]
1. `spcinvdj` - this clone is `GBF_VERSHOOT`, but should be `GBF_SHOOT`, as its parent is (and generally all Space Invaders should be).

2. `afighter` - I did not notice this when I reported this game in the previous issue, but it and all its clones in Sega 16A and 16B should actually be `GBF_VERSHOOT`, not horizontal.

3. these five are `GBF_VERSHOOT` but should be `GBF_HORSHOOT`:

```
hellfire
hvyunit
mshuttle
pballoon
zerowing
```

4. all these are `GBF_VERSHOOT` but they are not really shmups and should be `GBF_SHOOT` instead:

```
alinvade
buckrog
burnforc
combatsc
invaders
kingball
mirax
ozon1
redufo
sasuke
satansat
skybase
spaceskr
spcinv95
sstrangr
subroc3d
theend
victoryc
```

**Comment by Goratrix** [comment]
One more:

5. `assault` is `GBF_VERSHOOT`, which is correct, but clone `assaultj` is `GBF_SHOOT`, should be changed to `GBF_VERSHOOT`

**Comment by dinkc64** [comment]
Hi Goratrix,
They should be fixed now - thanks! :)

best regards,
- dink

**Comment by Goratrix** [comment]
Thank you! :-) Here's the last batch, a few clones that you missed that need to be aligned with their parent after the above changes, all are `GBF_VERSHOOT` but should be `GBF_SHOOT`:

`zone909`, clone of buckrog
`burnforco`, clone of burnforc
`kingballj`, clone of kingball
`zarzon`, clone of satansat

After these are fixed the issue can be closed :-)

**Comment by Goratrix** [comment]
Oh, here's one more, not Genre but Board Type:

`donight` should probably be Hack or Homebrew, not Genuine?

**Comment by dinkc64** [comment]
alright, got it! :)
