### ISSUE TITLE
Regulus (regulus) strange coin problem.. and maybe inverted fire buttons.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#254]
In Regulus options there are "1coin-1credit" selected but both COIN1 and COIN2 gives 2 credits for 1 coin.... strangely COIN1 sometimes gives 3 credits instead.

If you enter diagnostics you can spot a FIRE button first and BOMB button for second... in FBNEO the first button is BOMB and second is FIRE, instead.

Thanks.

**Comment by dinkc64** [comment]
I fixed the swapped fire/bomb buttons, but I'm not sure about the coinage part.  I'll have to ask for help :)

@barbudreadmon, can you have a look into this game in drv/sega/d_sys1.cpp - the coinage is fine here on standalone (1 coin = 1 credit)

**Comment by fastpop72** [comment]
Thank you! Fire buttons are now OK.

@barbudreadmon The coinage bug remains on libretro port... Both coins gives 2 credits each press for the first four times, the fifth time gives 3 credits... Very strange.

**Comment by fastpop72** [comment]
Opened the issue on libretro port. Closing...

**Comment by barbudreadmon** [comment]
The SYSTEM1_COINAGE macro seems wrong (duplicate setting for coinage), and the libretro port (which store dips setting through their string value) gets confused :  
https://github.com/finalburnneo/FBNeo/blob/d73464ad29879dea5dd1a33985baa87f5e8491ca/src/burn/drv/sega/d_sys1.cpp#L429-L430

As far as i can tell, the `0x0f` is the real "1 coin 1 credit" setting, while it seems the `0x00` should be "1 coin 2 credit 5/11" (for regulus, it seems different for other games). MAME seems to skip this `0x00` value, imho we should do the same.

**Comment by dinkc64** [comment]
Got it :)
what does the x/xx numbers mean on the coin/credit string?

**Comment by barbudreadmon** [comment]
5/11 = 5 coins 11 credits

**Comment by dinkc64** [comment]
oh! so a multi-coinage option.  I get it now :)

**Comment by dinkc64** [comment]
should be fixed now, right?

**Comment by barbudreadmon** [comment]
Yeah it is :)
